### ISSUE TITLE
Example (PART 1) fails with error

### ISSUE THREAD

**Issue by epogrebnyak** [click-contrib/click-configfile#11]
Where does `ConfigFileProcessor` gets imported from? 

I think running the example as is results in error.

**Comment by jenisys** [comment]
* Correct, the `PART 1` of the example is incomplete
* `PART 1` tells the first part of a story how everything fits together
* The complete and working example is at the bottom of the `README`.

NOTE:
Reading the complete `README` before complaining seems too much to be expected ;-)

**Comment by epogrebnyak** [comment]
> * Correct, the `PART 1` of the example is incomplete
> * `PART 1` tells the first part of a story how everything fits together
> * The complete and working example is at the bottom of the `README`.
> 
> NOTE: Reading the complete `README` before complaining seems too much to be expected ;-)

why not add all the necessary imports to top of first example?
would seem rather more natural

**Comment by jenisys** [comment]
Mmh, you seem to miss that a story is told in the README.
The story consists of multiple steps to make each step understandable and digestible. If you would only see the complete example, you would probable not understand how all parts fit together.
