### ISSUE TITLE
0.2.3 vs. 0.2.2

### ISSUE THREAD

**Issue by nixjdm** [click-contrib/click-configfile#3]
0.2.2 is the latest tag and release here on GitHub, but on PyPI there is a 0.2.3 as well. Not much has seemed to change, but nonetheless the changes should probably be pushed to GitHub and tagged to avoid confusion.

Version numbers changed in a few places. setup.cfg now has a block:
```
[egg_info]
tag_build = 
tag_date = 0
```

As far as I can tell those are the only differences.

**Comment by jenisys** [comment]
FIXED, pushed the "new version" to the Github repo; nothing has changed except the version number.
The main reason for this version was to change the URL on PyPI to the new repository location (meaning where it is now, HERE).
