### ISSUE TITLE
Inquiry on Repo Status

### ISSUE THREAD

**Issue by cascadianblue** [click-contrib/click-configfile#9]
Is this project still being maintained? I'm interested in using this lib in a project, but am hesitant to depend on a repo that has not had a release in three and a half years.

**Comment by kdeldycke** [comment]
I had the same issue about the lack of maintainership. I ended up re-implemented most of the features for my [`mpm` CLI project](https://github.com/kdeldycke/meta-package-manager).

What it does:
* Source config from a TOML file
* Allow the user to point to configuration location via a `-c/--config` option
* Search config file at default location: either `~/.<my-cli>/config.toml` (Linux & macOS) or `C:\Users\<user>\AppData\Roaming\<my-cli>\config.toml`(Windows)
* Ignore unrecognize options and settings
* Allow some options to by excluded (as requested in #8)
* Works with Click 8.x
* Has some unittets

The code, while not that clean nor perfect, is available at: https://github.com/kdeldycke/meta-package-manager/blob/develop/meta_package_manager/config.py . Maybe we can start a new project from that codebase.

**Comment by kdeldycke** [comment]
FYI, [configuration file utilities are being discussed](https://github.com/janluke/cloup/issues/96) for implementation in [Cloup, an actively maintained set of extensions](https://github.com/janluke/cloup) for Click.

**Comment by jenisys** [comment]
Yes, the project was somewhat inactive for a while.
I just brought it up to date again.

**Comment by kdeldycke** [comment]
For reference, I ended up releasing `click-extra`, a maintained add-on for Click that is adding all the [features I mentioned above](https://github.com/click-contrib/click-configfile/issues/9#issuecomment-922518307), including TOML, YAML and JSON support.
